version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: veteran_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yoursecurepassword
      POSTGRES_DB: veteran_healthcare
    ports:
      - "5432:5432"
    volumes:
      - veteran-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: veteran_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  veteran-pg-data: